apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: rso-store
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rso-store
        tier: frontend
    spec:
      containers:
      - image: tilen/rso-store
        name: apiseed
        ports:
        - containerPort: 3000
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: mongo
          - name: LOGZIO_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: logzio
          - name: NODE_ENV
            value: "prod"
          - name: DEPLOY_VERSION
            value: "%DEPLOY_VERSION%"
